lane_boundary:
  left:
  - x: 0.0
    y: 2.5
    z: 0.0
  - x: 10.0
    y: 2.5
    z: 0.0
  - x: 20.0
    y: 2.5
    z: 0.0
  - x: 30.0
    y: 2.5
    z: 0.0
  - x: 40.0
    y: 2.5
    z: 0.0
  - x: 50.0
    y: 2.5
    z: 0.0
  - x: 60.0
    y: 2.5
    z: 0.0
  - x: 70.0
    y: 2.5
    z: 0.0
  - x: 80.0
    y: 2.5
    z: 0.0
  - x: 90.0
    y: 2.5
    z: 0.0
  - x: 100.0
    y: 2.5
    z: 0.0
  right:
  - x: 0.0
    y: -2.5
    z: 0.0
  - x: 10.0
    y: -2.5
    z: 0.0
  - x: 20.0
    y: -2.5
    z: 0.0
  - x: 30.0
    y: -2.5
    z: 0.0
  - x: 40.0
    y: -2.5
    z: 0.0
  - x: 50.0
    y: -2.5
    z: 0.0
  - x: 60.0
    y: -2.5
    z: 0.0
  - x: 70.0
    y: -2.5
    z: 0.0
  - x: 80.0
    y: -2.5
    z: 0.0
  - x: 90.0
    y: -2.5
    z: 0.0
  - x: 100.0
    y: -2.5
    z: 0.0
entities:
- x: 25.0
  y: -3.5
  z: 1.0
  gamma: 3.14159
- x: 65.0
  y: -3.5
  z: 1.0
  gamma: 3.14159
car_pos:
  x: 0
  y: 0
  z: 0.0
  gamma: 0.0
