lane_boundary:
  left:
  - x: 0.0
    y: 2.5
    z: 0.0
  - x: 24.04
    y: 2.31
    z: 0.0
  - x: 49.04
    y: 27.31
    z: 0.0
  - x: 75.96
    y: 27.31
    z: 0.0
  - x: 101.77
    y: 1.77
    z: 0.0
  right:
  - x: 0.0
    y: -2.5
    z: 0.0
  - x: 25.96
    y: -2.31
    z: 0.0
  - x: 50.96
    y: 22.69
    z: 0.0
  - x: 74.04
    y: 22.69
    z: 0.0
  - x: 98.23
    y: -1.77
    z: 0.0
entities:
- x: 20.0
  y: -3.5
  z: 1.0
  gamma: 3.14159
- x: 70.0
  y: 21.5
  z: 1.0
  gamma: 3.14159
car_pos:
  x: 0
  y: 0
  z: 0.0
  gamma: 0.0
